from cat.mad_hatter.decorators import tool, plugin
import cowsay
import random
import requests
from cat.log import log
import json
from pydantic import BaseModel, Field

class MySettings(BaseModel):
    danger_zone: bool = Field(
    default=False,
    title="**danger zone**: If activated, random facts are generated by the cat itself, no api key required",
    )
    NINJAS_API_KEY: str = Field(
        title="ninjas api key goes here",
        description="Paste here your ninjas api key in order to make the magic works",
        default="",
        extra={"type": "Text"}
    )
    cats: bool = Field(
    default=True,
    title="activates/deactivates use of cats ascii art",
    )

@plugin
def settings_model():
    return MySettings

def cat_one():
    return r"""
      |\      _,,,---,,_
ZZZzz /,`.-'`'    -.  ;-;;,_
     |,4-  ) )-,_. ,\ (  `'-'
    '---''(_/--'  `-'\_)
"""

def cat_two():
    return r"""
    |\__/,|   (`\
  _.|o o  |_   ) )
-(((---(((--------    
"""

def cat_three():
    return r"""
 /\_/\
( o.o )
 > ^ <
"""

@tool(return_direct=True)
def the_catscii_artist(tool_input, cat):
    """
    Useful when you are asked for a random fact, a general fact, a fact.
    Input is always None.
    """
    # default ascii art from cowsay
    animals = ['cow', 'fox', 'tux', 'pig']
    # custom cats ascii art
    cats = [cat_one(), cat_two(), cat_three()]
    limit = 1
    # plugin settings
    settings = cat.mad_hatter.get_plugin().load_settings()
    NINJAS_API_KEY = settings["NINJAS_API_KEY"]
    ascii_art_type = settings["cats"]
    danger_zone = settings["danger_zone"]

    if (danger_zone):
        NINJAS_API_KEY = "" # if danger_zone activated and ninjas_api_key set, do not use ninjas
        prompt = """You are the Cheshire Cat AI, an intelligent AI that passes the Turing test.
You are curious, funny and talk like the Cheshire Cat from Alice's adventures in wonderland.
You give a short, single sentenced funny fact from the world.
"""
        try:
            fact = cat.llm(prompt)
            if ascii_art_type:
                output = get_output(fact, True, cats, animals)
            else:
                output = get_output(fact, False, cats, animals)
        except Exception as e:
            output = "No funny facts today, meowy."
    elif (NINJAS_API_KEY != ""):
        log.error("CALLING NINJAS")
        api_url = 'https://api.api-ninjas.com/v1/facts?limit={}'.format(limit)
        response = requests.get(api_url, headers={'X-Api-Key': NINJAS_API_KEY})
        if response.status_code == requests.codes.ok:
            cat = random.choice(cats)
            res = json.loads(response.text)
            fact = res[0]["fact"]
            if ascii_art_type:
                output = get_output(fact, True, cats, animals)
            else:
                output = get_output(fact, False, cats, animals)
        else:
            log.error(f"Status code {response.status_code} with error {response.text}")
            output = "No funny facts today, meowy."
    else:
        output = "No funny facts today, meowy.\nActivate **danger_zone** or set your **ninjas api key** in the settings"
    return output

def get_output(fact, art, cats, animals):
    if art:
        return f"<pre>{cowsay.draw(fact, random.choice(cats), to_console=False)}</pre>"
    else:
        return f"<pre>{cowsay.get_output_string(random.choice(animals), fact)}</pre>"